# Generated by Django 3.2.3 on 2023-04-03 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kitap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=2000)),
                ('author', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('file', models.FileField(blank=True, default=None, null=True, upload_to='')),
                ('text', models.TextField(blank=True, default=None, max_length=9999999, null=True)),
                ('score', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
    ]
